### ISSUE TITLE
Analysis To-Do Week of Aug 3

### ISSUE THREAD

**Issue by stephpenn1** [PNNL-PREMIS/PREMIS-sapflow#18]
- [x] Week cor calc: double check week calc range on plot
- [x] Week cor calc: place marker to sep years
- [x] PACF calc: make sure use filled in data
- [x] On that note: all dataframes should use filled in data ( put at beginning of Rmd )
- [x] Resolve PAR values (#19)
- [x] Constraints for matched days (#16)

**Comment by bpbond** [comment]
Thanks. One other request: if the `rs-js` branch can get pushed up somewhat regularly, that would be helpful in terms of my being able to stay up to date. 🙏

**Comment by stephpenn1** [comment]
Agreed, do you mean merged w `master` regularly or pushed from local? I do push to local with any new changes but haven't done a pull request in quite a while.

**Comment by bpbond** [comment]
I just pushed from local. Thanks.

**Comment by bpbond** [comment]
Are we keeping our scheduled Rs-Js meeting tomorrow?

**Comment by stephpenn1** [comment]
I am still working on some things that we talked about last week. Could we push to Friday by any chance?

**Comment by bpbond** [comment]
Okay.
